import { InsightsData } from '@/types/claude';

export function exportAsHTML(insights: InsightsData): void {
  const html = `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Claude Insights Report</title>
    <style>
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
            max-width: 1200px;
            margin: 0 auto;
            padding: 40px 20px;
            background-color: #f5f5f5;
            color: #333;
        }
        h1 {
            color: #2563eb;
            border-bottom: 3px solid #2563eb;
            padding-bottom: 10px;
        }
        .metrics-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
            gap: 20px;
            margin: 30px 0;
        }
        .metric-card {
            background: white;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }
        .metric-label {
            font-size: 14px;
            color: #666;
            margin-bottom: 8px;
        }
        .metric-value {
            font-size: 32px;
            font-weight: bold;
            color: #2563eb;
        }
        .section {
            background: white;
            padding: 30px;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
            margin: 20px 0;
        }
        h2 {
            color: #2563eb;
            margin-top: 0;
        }
        table {
            width: 100%;
            border-collapse: collapse;
        }
        th, td {
            padding: 12px;
            text-align: left;
            border-bottom: 1px solid #e5e7eb;
        }
        th {
            background-color: #f9fafb;
            font-weight: 600;
        }
        .footer {
            text-align: center;
            margin-top: 40px;
            color: #666;
            font-size: 14px;
        }
    </style>
</head>
<body>
    <h1>Claude Insights Report</h1>
    <p>Generated on ${new Date().toLocaleString()}</p>

    <div class="metrics-grid">
        <div class="metric-card">
            <div class="metric-label">Total Conversations</div>
            <div class="metric-value">${insights.totalConversations.toLocaleString()}</div>
        </div>
        <div class="metric-card">
            <div class="metric-label">Total Messages</div>
            <div class="metric-value">${insights.totalMessages.toLocaleString()}</div>
        </div>
        <div class="metric-card">
            <div class="metric-label">Your Messages</div>
            <div class="metric-value">${insights.userMessages.toLocaleString()}</div>
        </div>
        <div class="metric-card">
            <div class="metric-label">Claude's Messages</div>
            <div class="metric-value">${insights.assistantMessages.toLocaleString()}</div>
        </div>
    </div>

    <div class="section">
        <h2>Overview</h2>
        <p><strong>Date Range:</strong> ${insights.dateRange.start} to ${insights.dateRange.end}</p>
        <p><strong>Average Messages per Conversation:</strong> ${insights.avgMessagesPerConversation}</p>
        <p><strong>Longest Conversation:</strong> ${insights.longestConversation.name} (${insights.longestConversation.messageCount} messages)</p>
    </div>

    <div class="section">
        <h2>Top 10 Conversations</h2>
        <table>
            <thead>
                <tr>
                    <th>Conversation Name</th>
                    <th>Messages</th>
                    <th>Created</th>
                </tr>
            </thead>
            <tbody>
                ${insights.topConversations.map(conv => `
                    <tr>
                        <td>${conv.name}</td>
                        <td>${conv.messageCount}</td>
                        <td>${new Date(conv.created).toLocaleDateString()}</td>
                    </tr>
                `).join('')}
            </tbody>
        </table>
    </div>

    <div class="section">
        <h2>Conversation Length Distribution</h2>
        <table>
            <thead>
                <tr>
                    <th>Message Range</th>
                    <th>Number of Conversations</th>
                </tr>
            </thead>
            <tbody>
                ${insights.conversationLengthDistribution.map(dist => `
                    <tr>
                        <td>${dist.range} messages</td>
                        <td>${dist.count}</td>
                    </tr>
                `).join('')}
            </tbody>
        </table>
    </div>

    <div class="footer">
        <p>This report was generated by Claude Insights - A privacy-first analytics tool for your Claude data.</p>
        <p>All processing was done locally in your browser. No data was sent to any server.</p>
    </div>
</body>
</html>
  `.trim();

  const blob = new Blob([html], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `claude-insights-${new Date().toISOString().split('T')[0]}.html`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function exportAsJSON(insights: InsightsData): void {
  const json = JSON.stringify(insights, null, 2);
  const blob = new Blob([json], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `claude-insights-${new Date().toISOString().split('T')[0]}.json`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
